---
Name: Dublove
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'dublove'
SiteConfig:
  extensions:
    - SiteConfigExtension
FormSpamProtectionExtension:
  default_spam_protector: NocaptchaProtector

NocaptchaField:
    site_key: "6LfgViQTAAAAAJsKO-tItY_7pvfJdO1uup7fWQyb"
    secret_key: "6LfgViQTAAAAAD5afLtL6tshB9-ZQLUWsT-oqX1q"
    verify_ssl: true
    default_theme: "light"
    default_type: "image"
    default_size: "normal"
